---
title: "UltimatumAnalysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
library(pacman)
p_load(tidyverse, rethinking, pastecs, patchwork, Brobdingnag)

getwd()
locpath= getwd()
setwd(locpath)

U8 = read.csv("~/Desktop/4. semester/Soc_Cult/Soc_cult_repository/S8/ultimatumS8_p.csv")
write.csv(U8, file = "U8.csv")
# _________________________________________________________________________________________

# Data

# loading data 
d1 = read.csv("U1.csv")
d2 = read.csv("U2.csv")
d3 = read.csv("U3.csv")
d4 = read.csv("U4.csv")
d5 = read.csv("U5.csv")
d6 = read.csv("U6.csv")
d7 = read.csv("U7.csv")

# cleaning up in unnessecary columns, making new data frame without NAs, scaling data to be able to build models
d = rbind(d1, d2, d3, d4, d5, d6, d7)
df = data.frame(d$participant.id_in_session, d$participant.time_started, d$participant.payoff, d$player.id_in_group, d$player.team, d$player.age, d$player.gender, d$player.group_id, d$player.payoff, d$group.amount_offered, d$group.offer_accepted, d$subsession.round_number, d$between_group_play)

df = df[complete.cases(df),] 
# str(df) checking if the data can be standardized (remove factors - gender + timestamp)
# ?? making gender an integer: df$gender <- ifelse(df$player.gender == "female", 0, 1)
df <- df[, -c(2,7)] 

# we don't want to scale all columns 
df_1 = data.frame(df$d.participant.id_in_session, df$d.player.id_in_group, df$d.player.team,df$d.player.group_id, df$d.group.offer_accepted, df$d.subsession.round_number, df$d.between_group_play)  # add group_number
df <- df[, -c(1,3,4,6,9,10,11)] # add column number for variable group number 

# standardizing the data (centering and scaling)
df_s = scale(df, center = TRUE, scale = TRUE)
df_s = as.data.frame(df_s)

# new data frame
df = cbind(df_1, df_s)

# ______________________________________________________________________________________________

# Pipes 

# looking at winning vs losing teams 
team_cond_sum = data1 %>%
  group_by(d.player.team == '1') %>% 
   summarise(offered = mean(d.group.amount_offered))
team_cond_sum
# very similar regardless of winning or losing (T=51.4, F=50)

# looking at offers between and within groups 
group_type_sum = data1 %>%
  group_by(d.between_group_play == '1') %>% 
   summarise(offered = mean(d.group.amount_offered))
group_type_sum
# here we see a bit more of a difference (T=48.9, F=54)

comb_sum = data1 %>%
  group_by(d.between_group_play == '1', d.player.team == '1') %>% 
   summarise(offered = mean(d.group.amount_offered))
comb_sum
# (F/F=52, F/T=56, T/F=48.9, T/T=48.9)

## pipes looking at acceptance rate 

# looking at overall acceptance rates 
sum(data1$d.group.offer_accepted == '1') # 40
sum(data1$d.group.offer_accepted == '0') # 16

# winning or losing rate of acceptance 
team_cond_rate = data1 %>%
  group_by(d.player.team == '1') %>% 
   summarise(accept_rate = sum(d.group.offer_accepted == '1'))
team_cond_rate
# (F=19,T=21)

# very similar regardless of winning or losing 
team_cond_rate1 = data1 %>%
  group_by(d.player.team == '1') %>% 
   summarise(accept_rate = sum(d.group.offer_accepted == '0'))
team_cond_rate1
# (F=9, T=7)

# looking at offers between and within groups 
group_type_rate = data1 %>%
  group_by(d.between_group_play == '1') %>% 
   summarise(accept_rate =  sum(d.group.offer_accepted == '1'))
group_type_rate
# (F=18, T=22)

group_type_rate1 = data1 %>%
  group_by(d.between_group_play == '1') %>% 
   summarise(accept_rate =  sum(d.group.offer_accepted == '0'))
group_type_rate1
# (F=2, T=14)

# combining all 
comb_rate = data1 %>%
  group_by(d.between_group_play == '1', d.player.team == '1') %>% 
   summarise(accept_rate = sum(d.group.offer_accepted == '1'))
comb_rate
# (F/F=8, F/T=10, T/F=11, T/T=11)

comb_rate1 = data1 %>%
  group_by(d.between_group_play == '1', d.player.team == '1') %>% 
   summarise(accept_rate = sum(d.group.offer_accepted == '0'))
comb_rate1
# (F/F=2, F/T=0, T/F=7, T/T=7)

# _____________________________________________________________________________________________

# MODELS

# amount offered ~ condition w/l
# amount offered ~ in group / out group 
# amount offered ~ condition + group 
# amount offered ~ condition * group + (1|particpant) + (1|experiment session) 

# acceptance rate ~ condition w/l
# acceptance rate ~ in group / out group 
# acceptance rate ~ condition + group 
# acceptance rate ~ condition * group

################

# run all four models and do the waic, 
# random effect - participant and session.group, (1|particpant) + (1|experiment session) 
# run the R.sim on the best model 
# centered at 0 and very certain, or evry uncertain 
# skeptical prior 0.2 (acceptance binomial, rate of binomial distribution(probability to accpet is a linear model which is the same as in the amount offered but also have an interaction))
# amount offered = normal, acceptance rate a map2stan binomail

# acceptance rate ~ team
m1 <- map2stan(
  alist(
    df.d.group.offer_accepted ~ dbinom( 1, p ) ,
    logit(p) <- a[df.d.participant.id_in_session] + b[df.d.player.team] + (bA*df.d.player.team),
    a[df.d.participant.id_in_session] ~ dnorm(0,1),
    b[df.d.player.team] ~ dnorm(0,1),
    bA ~ binom(0,0.2) , 
    a ~ dnorm(0,1) ,
    b ~ dnorm( 0 , 1 ) , 
    sigma ~ dunif( 0 , 3 ) ,
  ),
  data = df,
  chains = 4, cores = 2, iter = 5000, warmup = 3000
)


#    mu <- a + (1|df.d.participant.id_in_session) + (1|group effect) + b*df.d.player.team ,


# model for amount offered 
m1 <- map(
  alist(
    d.group.amount_offered ~ dnorm( mu , sigma ) , 
    mu <- a + (1|df.d.participant.id_in_session) + (1|group effect) + b*df.d.player.team ,
    ap ~ a ~ dnorm( 0 , 1 ) , 
    b ~ binom( 0 , 1 ) , 
    sigma ~ dunif( 0 , 3 )
  ) ,
  data= df)

precis(m1)
plot(precis(m1))


# model adding between group play 
m2 <- rethinking::map(
  alist(
    d.group.amount_offered ~ dnorm( mu , sigma ) , 
    mu <- a + b*df.d.player.team +c*d.between_group_play ,
    a ~ dnorm( 0 , 1 ) , 
    b ~ dnorm( 0 , 1 ) , 
    c ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 3 )
  ) ,
  data= df)

precis(m2)
plot(precis(m2))

# model looking at acceptance rate 
m3 <- rethinking::map(
  alist(
    df.d.group.offer_accepted ~ dnorm( mu , sigma ) , 
    mu <- a + b*df.d.player.team,
    a ~ dnorm( 0 , 1 ) , 
    b ~ dnorm( 0 , 1 ) , 
    sigma ~ dunif( 0 , 3 )
  ) ,
  data= df)


### 
m7.5 <- map(
    alist(
        log_gdp ~ dnorm( mu , sigma ) ,
        mu <- a + gamma*rugged + bA*cont_africa ,
        gamma <- bR + bAR*cont_africa ,
        a ~ dnorm( 8 , 100 ) ,
        bA ~ dnorm( 0 , 1 ) ,
        bR ~ dnorm( 0 , 1 ) ,
        bAR ~ dnorm( 0 , 1 ) ,
        sigma ~ dunif( 0 , 10 )
), data=dd )



precis(m3)
plot(precis(m3))
devtools::install_github("rmcelreath/rethinking", force = TRUE)
library(rstan)
# model looking at acceptance rate 
m4 <- rethinking::map(
  alist(
    df.d.group.offer_accepted ~ dnorm( mu , sigma ) , 
    mu <- a + b*df.d.player.team +c*d.between_group_play ,
    a ~ dnorm( 0 , 1 ) , 
    b ~ dnorm( 0 , 1 ) , 
    c ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 3 )
  ) ,
  data= df)

precis(m4)
plot(precis(m4))

m <- map(
  alist(
    df.d.group.offer_accepted ~ dbinom(df.d.player.team, p) , 
    logit(p) <- a + bB*df.d.between_group_play ,
    a ~ dnorm(0,1) ,
    Bb ~ (0,1) 
  ) ,
  data = df ) 

    
  )
)

## we want pretty plots 
condidion = group_number 
group = between_group_play
AV, AW ! 

```

## Including Plots














You can also embed plots, for example:

```{r pressure, echo=FALSE}
# want boxplots maybe? how do we get this of pipes? 
# plots of model predictions 
# plots of likelihood functions 
# anything else? 
# do we want posterior predictive plots maybe? 
# plot simulated posteriors against actual posteriors, do we want this? 

gggplot = function(model, x = NULL , y = NULL, dataframe){ 
   #where: 
  #model is a model resulting from MAP 
  #x is the x variable as a string (can be left unspecified) 
  #y is the y variable as a string (can be left unspecified) 
  #dataframe is the dataframe from which the model is trained upon 
  #requires packages: dplyr, ggplot2, stringr and rethinking
  
  if (is.null(y) == T){ 
    #if y isn't specified - extract y 
    temp <- flist_untag(model@formula)[[1]] 
    y <- as.character(temp[[2]])
    } 
  if (is.null(x) == T){ 
    #if x isn't specified - extract x 
      temp <- flist_untag(model@formula)[[2]] 
      x <- gsub(" ","",gsub(".*\\*","",as.character(temp[[3]])[3])) 
  }
  
   #extracting data from the dataframe 
  xd <- dplyr::select(dataframe, x) 
  yd <- dplyr::select(dataframe, y)
  
  
   #calculate the prior data 
  post <- extract.samples(model) 
  #posterior from samples 
  mu.link <- function(x) post$a + post$b*x 
  VIQ.seq <- seq( from=min(xd) , to=max(xd) , by=0.1 ) 
  mu <- sapply( VIQ.seq , mu.link ) 
  mu.mean <- apply( mu , 2 , mean ) 
  mu.HPDI <- apply( mu , 2 , HPDI , prob=0.89 ) 
  temp_list = list(VIQ.seq); names(temp_list) <- x 
  #naming the vector in the list (since the sim function requires it) 
  sim.VIQ <- sim( model , data=temp_list ) 
  VIQ.PI <- apply( sim.VIQ , 2 , PI , prob=0.89 )

  #transform the data from ggplot 
    #for making the line 
  temp_df <- data.frame(VIQ.seq = VIQ.seq, mu.mean = mu.mean) 
  #for making the HDPI 
  temp_matrix <- t(data.frame(mu.HPDI = mu.HPDI)) 
  #t() is a tranpose function which returns a matrix 
  temp_df1 = data.frame(lower = temp_matrix[,1], upper = temp_matrix[,2], mu.mean = mu.mean, VIQ.seq = VIQ.seq)
   #for making the PI 
  temp_matrix <- t(data.frame(VIQ.PI = VIQ.PI)) 
  temp_df2 = data.frame(lower = temp_matrix[,1], upper = temp_matrix[,2], mu.mean = mu.mean, VIQ.seq = VIQ.seq) 
  #for the points 
  dataframe = data.frame(xd, yd) 
  #taking the data to new column as to chose the name (maintaining old name for the names on the plot) 
  dataframe$c1 = dataframe[,1] 
  dataframe$c2 = dataframe[,2]
  
   #make the plot 
  grob = ggplot(dataframe, aes(x = c1, y = c2)) + 
    geom_ribbon(data = temp_df2, aes(x = VIQ.seq, y = mu.mean, ymin = lower, ymax = upper), fill = "grey70", alpha = 2/3) + 
    geom_ribbon(data = temp_df1, aes(x = VIQ.seq, y = mu.mean, ymin = lower, ymax = upper), fill = "grey83", alpha = 2/3) + 
    geom_line(data = temp_df, aes(x = VIQ.seq, y = mu.mean))+ 
    geom_point(color = "navyblue", shape = 1, size = 1.5, alpha = 2/3)+ 
    xlab(colnames(dataframe)[1]) + 
    ylab(colnames(dataframe)[2]) 
  #using the names for the axis 
  return(grob) 
  } #go go gadget fancy plot

#plotting predictions
p1 = gggplot(m1, x = 'd.player.team', y = 'd.group.amount_offered', dataframe = dataS) +
  ggtitle("Model 1")
p1

p2 

p3 

p4 

p1 + p2 + p3 + p4 


# repeat for them all and put together 

#plotting likelihood (remake to exam data)
dens(dataS$d.group.amount_offered[dataS$d.player.team == "1"], col='red')
dens(dataS$d.group.amount_offered[dataS$d.player.team == "2"], add = T)

dens(dataS$d.group.amount_accepted[dataS$d.player.team == "1"], col='red')
dens(dataS$d.group.amount_accepted[dataS$d.player.team == "2"], add = T)

dens(dataS$d.group.amount_offered[dataS$d.between_group_play == "1"], col='red')
dens(dataS$d.group.amount_offered[dataS$d.between_group_play == "0"], add = T)

dens(dataS$d.group.amount_accepted[dataS$d.between_group_play == "1"], col='red')
dens(dataS$d.group.amount_accepted[dataS$d.between_group_play == ""], add = T)


#plotting liklihood distributions (ggplot) 
ggplot(dataS, aes(x = d.group.amount_offered, color = d.player.team)) + 
  geom_density()


df$group = df[1]

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
